config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:sessions]

  as :user do
    get ":uid/mark-all-read" => "users#read_all", as: :read_all_activities
    get "read/:uid" => "users#read_activity", as: :read_activity
    get "login" => "sessions#new", as: :new_user_session
    post 'login' => 'sessions#create', as: :user_session
    get "logout" => "sessions#destroy", as: :logout
  end

  root "users#dashboard"

  resources :tasks do
    member do
      get :view_comments
    end
  end
  resources :contacts do
    member do
      get :view_comments
    end
  end
  resources :comments, only: [:edit, :create, :update, :destroy]
end

app/models/task.rb
class Task < ActiveRecord::Base
	include Tokenable
	has_paper_trail ignore: [:updated_at, :created_at, :uid, :contact_sort, :main_sort]

	belongs_to :user
	belongs_to :contact
	acts_as_commentable

	scope :overdue, -> { where("due_date < ?", Date.today)}
	scope :current, -> { where("due_date >= ?", Date.today)}
	scope :not_due, -> { where(due_date: nil)}


	def to_param
		uid
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :view_comments, :destroy]
  before_action :set_contact, only: [:new]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  def view_comments
    @comment = Comment.new
    @comments = @task.comments
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @comment = Comment.new

    if @task.save
      @activity = PublicActivity::Activity.create trackable: @task, key: 'task.created', owner: current_user, parameters: { url: @task.contact.present? ? contact_path(@task.contact) : root_url }, uid: Activity.new().generate_token
      Activity.find(@activity.id).mark_as_read! :for => current_user
    end

    respond_to do |format|
      format.html { redirect_to params[:return_url] || root_path }
      format.js
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @comment = Comment.new

    if @task.update(task_params)
      if params[:quick_complete]
        if @task.completed?
          @activity = PublicActivity::Activity.create trackable: @task, key: 'task.completed', owner: current_user, parameters: {changes: @task.versions.last.changeset, url: @task.contact.present? ? contact_path(@task.contact) : root_url }, uid: Activity.new().generate_token if @task.completed
          Activity.find(@activity.id).mark_as_read! :for => current_user
        else
          @activities = Activity.where(trackable_type: "Task", trackable_id: @task.id, key: "task.completed")
          @remove_these = @activities.dup
          puts @remove_these.inspect
          @activities.delete_all
          puts @remove_these.inspect
        end
      else
        if @task.completed?
          @activity = PublicActivity::Activity.create trackable: @task, key: 'task.completed', owner: current_user, parameters: {changes: @task.versions.last.changeset, url: @task.contact.present? ? contact_path(@task.contact) : root_url }, uid: Activity.new().generate_token if @task.completed
          Activity.find(@activity.id).mark_as_read! :for => current_user
        else
          PublicActivity::Activity.where(trackable_type: "Task", trackable_id: @task.id, key: "task.completed").delete_all
          @activity = PublicActivity::Activity.create trackable: @task, key: 'task.updated', owner: current_user, parameters: {changes: @task.versions.last.changeset, url: @task.contact.present? ? contact_path(@task.contact) : root_url }, uid: Activity.new().generate_token
          Activity.find(@activity.id).mark_as_read! :for => current_user
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to params[:return_url] || root_path }
      format.js
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find_by(uid: params[:id])
    end

    def set_contact
      @contact = Contact.find_by(uid: params[:contact_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params[:task][:due_date] = Chronic.parse(params[:task][:due_date]) if params[:task][:due_date].present?
      params.require(:task).permit(:content, :completed, :due_date, :contact_id, :user_id, :contact_sort, :main_sort, :uid)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task, url: @task.new_record? ? tasks_path(return_url: request.referrer) : task_path( @task, return_url: request.referrer)  do |f| %>
  <%= link_to "#", class: "btn btn-default btn-sm-round cancel-edit" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
  <% end %>
<% if @task.new_record? %>
    <h2>New Task</h2>
<% else %>
    <h2>Edit Task</h2>
<% end %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, "Details" %>
    <%= f.text_area :content %>
  </div>
  <% unless @task.new_record? %>
    <div class="field">
      <%= f.label :completed, class: "control checkbox", for: nil do %>
        <span class="name">Completed</span>
        <%= f.check_box :completed, class: "checkbox" %>
        <span class="control-indicator"></span>
        <span class="control-text">&nbsp;</span>
      <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :due_date, class: "select" do %>
      <span class="name">Due Date</span>
      <div class="bfh-datepicker"></div>
      <span class="<%= @task.due_date.present? ? 'clear-date glyphicon glyphicon-remove' : 'hide clear-date glyphicon glyphicon-remove' %>"></span>
    <% end %>
    <script>
     $(document).ready(function(){
        $(document).on('change.bfhdatepicker', '.bfh-datepicker', function(){
          if ($(this).val() != "") {
            $('.clear-date').removeClass('hide');
          }
        })
        $(document).on('click', '.clear-date', function(){
          $('.bfh-datepicker').val('');
          $('.clear-date').addClass('hide');
        });
     });
    </script>
  </div>
  <div class="<%= @contact.present? ? "hide field" : "field" %>">
    <%= f.label :contact_id, class: "select" do %>
      <span class="name">Contact</span>
      <%= f.select :contact_id, options_from_collection_for_select(Contact.all.order(:name), :id, :name, @task.contact_id || (@contact.present? ? @contact.id : nil)), class: 'select', include_blank: true %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :user_id, class: "select" do %>
      <span class="name">Assignee</span>
      <%= f.select :user_id, options_from_collection_for_select(User.all.order(:name), :id, :name, @task.user_id), class: 'select', include_blank: true %>
    <% end %>
  </div>

  <div class="actions">
    <div class="row">
      <div class="col-md-6">
        <%= link_to "#", class: "btn btn-default btn-block cancel-edit" do %>
          Cancel
        <% end %>
      </div>
      <div class="col-md-6">
        <%= f.submit class: 'btn btn-default-inverted btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li class="task <%= task.due_date.present? && task.due_date < Date.today ? "overdue" : nil %> <%= task.completed ? 'completed' : nil %>" data-task-id="<%= task.uid %>">
	<%= form_for task, html: {class: "complete-form" }, remote: true do |f| %>
		<%= f.label :completed, class: "control checkbox", for: nil do %>
			<%= f.check_box :completed %>
			<%= hidden_field_tag :quick_complete, true%>
			<span class="control-indicator"></span>
    <% end %>
  <% end %>
	<span class="content"> 
    <% if task.due_date.present? && task.due_date < Date.today && params[:sort_by] != "due_date" && params[:sort_by].present? %>
      <span class="glyphicon glyphicon-exclamation-sign tooltip-it" data-title="Due on: <%= task.due_date.strftime("%m/%d/%y") %>" data-placement="right" data-toggle="tooltip"></span>
    <% end %>
    <%= simple_format(task.content) %>
  </span>
	<span class="meta"><%= link_to view_comments_task_path(task), class: "", remote: true do %>  <%= task.comments.count %> &nbsp; <span class="glyphicon glyphicon-comment"> </span> <% end %> &nbsp; <%= link_to edit_task_path(task), remote: true do %> <span class="glyphicon glyphicon-pencil"></span> <% end %> &nbsp; <%= link_to task_path(task),method: :delete, remote: true do  %> <span class="glyphicon glyphicon-trash"></span> <% end %></span>
	
</li>

app/views/tasks/_tasks.html.erb
<% if params[:sort_by] == "client" %>
  <% @task_groups.sort.each do |contact, tasks| %>
    <% if contact.present? %>
      <%= User.find_by(name: contact) %>
        <span class="task-contact"><%= link_to contact, Contact.find_by(name: contact) %></span>
    <% end %>
    <ul>
      <% tasks.each do |task| %>
        <%= render task %>
      <% end %>
    </ul>
  <% end %>
<% else %>
   <% if Task.overdue.any? %>
    <span class="task-contact overdue">Overdue</span>
    <ul>
      <% Task.overdue.each do |task| %>
        <%= render task %>
      <% end %>
    </ul>
  <% end %>
  <% @task_groups.sort.each do |contact, tasks| %>
    <% if contact.present? %>
      <% if params[:sort_by] != "client" %>
        <% if contact == Date.today.strftime("%m/%d/%y").to_s %>
           <span class="task-contact today">Today</span>
        <% else %>
           <span class="task-contact"><%= contact %></span>
        <% end %>
      <% else %>
        <span class="task-contact"><%= contact %></span>
      <% end %>
    <% end %>
    <ul>
      <% tasks.each do |task| %>
        <%= render task %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/tasks/create.js.erb
$('#right_sidebar, body').removeClass('editing');
$('#form_container').html(" ");
$('#tasks ul').append("<%= j render @task %>")

app/views/tasks/destroy.js.erb
if ($('li[data-task-id="<%= @task.uid %>"]').parent().children().length <=1 ) {
	$('li[data-task-id="<%= @task.uid %>"]').parent().prev('.task-contact').remove();
	$('li[data-task-id="<%= @task.uid %>"]').parent().remove();
} else {
	$('li[data-task-id="<%= @task.uid %>"]').remove();
}

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#right_sidebar, body').addClass('editing');
$('#form_container').html("<%= j render 'form' %>")
$('.bfh-datepicker').bfhdatepicker({'name': 'task[due_date]', 'date': '<%= @task.due_date.present? ? @task.due_date.strftime("%m/%d/%Y") : nil %>'});
$('#task_content').focus();

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Completed</th>
      <th>Due date</th>
      <th>Contact</th>
      <th>User</th>
      <th>Contact sort</th>
      <th>Main sort</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.completed %></td>
        <td><%= task.due_date %></td>
        <td><%= task.contact_id %></td>
        <td><%= task.user_id %></td>
        <td><%= task.contact_sort %></td>
        <td><%= task.main_sort %></td>
        <td><%= task.uid %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#right_sidebar, body').addClass('editing');
$('#form_container').html("<%= j render 'form' %>")
$('.bfh-datepicker').bfhdatepicker({'name': 'task[due_date]', 'date': '<%= @task.due_date.present? ? @task.due_date.strftime("%m/%d/%Y") : nil %>'});
$('#task_content').focus();

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @task.contact_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Contact sort:</strong>
  <%= @task.contact_sort %>
</p>

<p>
  <strong>Main sort:</strong>
  <%= @task.main_sort %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @task.uid %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#right_sidebar, body').removeClass('editing');
$('#form_container').html(" ");

$('li[data-task-id="<%= @task.uid %>"]').replaceWith('<%= j render @task %>');

<% if @task.completed? %>
	$('li[data-task-id="<%= @task.uid %>"]').addClass('completed');
<% else %>
	$('li[data-task-id="<%= @task.uid %>"]').removeClass('completed');
<% end %>

console.log('<%= @remove_these.inspect %>')
<% if @remove_these.present? %>
	<% @remove_these.each do |activity| %>
			$('li[data-activity-id="<%= activity.uid %>"]').remove();
	<% end %>
<% end %>

app/views/tasks/view_comments.js.erb
$('#modals').html('<%= j render "comments/comments_modal", contact: @contact %>')
$('.modal').modal({
  keyboard: false,
  show: true,
  backdrop:true
})