config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:sessions]

  as :user do
    get ":uid/mark-all-read" => "users#read_all", as: :read_all_activities
    get "read/:uid" => "users#read_activity", as: :read_activity
    get "login" => "sessions#new", as: :new_user_session
    post 'login' => 'sessions#create', as: :user_session
    get "logout" => "sessions#destroy", as: :logout
  end

  root "users#dashboard"

  resources :tasks do
    member do
      get :view_comments
    end
  end
  resources :contacts do
    member do
      get :view_comments
    end
  end
  resources :comments, only: [:edit, :create, :update, :destroy]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include PublicActivity::Common
	include Tokenable
	has_paper_trail ignore: [:updated_at, :created_at, :uid]
	acts_as_commentable

	enum contact_type: [ :agent, :client, :lender, :vendor ]
	enum transaction_type: [ :sale, :purchase, :lease, :sale_and_purchase, :sale_and_lease ]

	has_many :tasks, dependent: :destroy


	def loop_url
		"https://www.dotloop.com/my/loops/#{loop_id}"
	end

	def to_param
		uid
	end

	def pretty_transaction
		transaction_type.gsub("_", " ").titleize
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :view_comments, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    case params[:group]
    when "agents"
      @contacts = Contact.agent.order("name")
    when "clients"
      @contacts = Contact.client.order("name")
    when "lenders"
      @contacts = Contact.lender.order("name")
    when "vendors"
      @contacts = Contact.vendor.order("name")
    else
      @contacts = Contact.all.order("name")
    end
    @contacts = @contacts.where("LOWER(name) like ?", "%#{params[:search].downcase}%") if params[:search]
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @comment = Comment.new

    if params[:assigned_to].present?
      @user = User.find_by(name: params[:assigned_to])
      @tasks = @contact.tasks.where(user_id: @user.id)
    else
      @tasks = @contact.tasks
    end

    @task_groups = @tasks.group_by{ |t| t.due_date.present? ? t.due_date.strftime("%m.%d.%y") : "No Due Date" }
  end

  def view_comments
    @comment = Comment.new
    @comments = @contact.comments
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    logger.debug "here"
    respond_to do |format|
      format.js
    end
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @group = params[:group]
    respond_to do |format|
      if @contact.save
         @activity = PublicActivity::Activity.create trackable: @contact, key: 'contact.created', owner: current_user, parameters: { url: contact_path(@contact) }, uid: Activity.new().generate_token
         Activity.find(@activity.id).mark_as_read! :for => current_user

        format.html { redirect_to @contact }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        @activity = PublicActivity::Activity.create trackable: @contact, key: 'contact.updated', owner: current_user, parameters: {changes: @contact.versions.last.changeset, url: contact_path(@contact) }, uid: Activity.new().generate_token
        Activity.find(@activity.id).mark_as_read! :for => current_user
        format.html { redirect_to @contact }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.includes(:tasks).find_by(uid: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:contact_type, :transaction_type, :status, :name, :email, :phone, :company, :street, :city, :state, :postal_code, :service, :dot_loop_id, :notes)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<li class="contact" data-contact-id="<%= contact.uid %>">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <%= link_to contact do %>
          <span class="identity name"><%= contact.name %></span>
          <span class="identity details"><%= "#{contact.transaction_type.gsub("_", " ").titleize}" %></span>
        <% end %>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: 10px;">
        <div class="meta">
          <span ><%= link_to view_comments_contact_path(contact), remote: true do %> <%= pluralize(contact.comments.count, "Comment") %> <% end %> | <%= pluralize(contact.tasks.count, "Task") %>
          </span>
        </div>
      </div>
    </div>
</li>

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
  <%= link_to "#", class: "btn btn-default btn-sm-round cancel-edit" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
  <% end %>
  <% if @contact.new_record? %>
    <h2>New<br><%= params[:group] == "client" ? "Client" : "Contact" %></h2>
  <% else %>
    <h2>
      <% if @contact.name.length > 10 %>
        <%= @contact.name.split[0] %><br> <%= @contact.name.split[1] %>
      <% else %>
        <%= @contact.name %>
      <% end %>
    </h2>
  <% end %>

  <div class="clearfix"></div>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="<%= params[:group] == "client" ? "hide field" : "field" %>">
    <%= f.label :contact_type,  class: "select" do %>
      <span class="name">Type</span>
      <%= f.select :contact_type, options_for_select([["Agent", "agent"], ["Client", "client"], ["Lender", "lender"], ["Vendor", "vendor"]], @contact.new_record? ? (params[:group].present? ? params[:group] : nil): @contact.contact_type)%>
    <% end %>
  </div>

  <div class="vendor-fields <%= @contact.contact_type == "vendor" ? nil : "hide" %>">
    <div class="field">
      <%= f.label :company, "Company Name" %>
      <%= f.text_field :company %>
    </div>
    <div class="field">
      <%= f.label :service, "Service Provided" %>
      <%= f.text_field :service %>
    </div>
    <hr>
  </div>

  <div class="client-fields <%= @contact.contact_type == "client" || params[:group] == "client" ? nil : "hide" %>">
    <div class="field">
      <%= f.label :transaction_type, class: "select" do %>
        <span class="name">Transaction Type</span>
        <%= f.select :transaction_type, options_for_select([["Sale", "sale"], ["Purchase", "purchase"], ["Lease", "lease"],["Sale & Purchase", "sale_and_purchase"],["Sale & Lease", "sale_and_lease"]], @contact.transaction_type)%>
      <% end %>
    </div>

    <div class="<%= params[:group] == "client" ? "hide field" : "field" %>">
      <%= f.label :status, class: "control checkbox" do %>
        <span class="name">Active Client</span>
        <%= f.check_box :status, class: "checkbox", checked: params[:group] == "client" %>
        <span class="control-indicator"></span>
        <span class="control-text">Is this an active client?</span>
      <% end %>
    </div>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <%= hidden_field_tag :group, params[:group] %>
  <div class="actions">
    <div class="row">
      <div class="col-md-6">
        <%= link_to "Cancel", "#", class: "btn btn-default btn-block cancel-edit" %>
      </div>
      <div class="col-md-6">
        <%= f.submit class: 'btn btn-default-inverted btn-block' %>
      </div>
    </div>
    <% unless @contact.new_record?  %>
      <div class="row row-bottom">
        <div class="col-md-12">
          <%= link_to contact_path(@contact), method: :delete, class: "text-muted pull-right",
    data: {confirm: "Are you sure you want to delete this contact?", confirm_fade: true, confirm_title: "Delete Contact", confirm_cancel: "Cancel", confirm_cancel_class: "btn-default", confirm_proceed: "Delete", confirm_proceed_class: "btn-default-inverted" } do %>
            <span class="glyphicon glyphicon-trash"></span> Delete Contact?
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>

app/views/contacts/create.js.erb
$('#right_sidebar, body').removeClass('editing');
$('#form_container').html(" ");
<% if @group.singularize == @contact.contact_type %>
	$('ul.contacts').html("<%= j render Contact.where(contact_type: @contact[:contact_type]) %>")
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/edit.js.erb
$('.contact').removeClass('editing');
$('#right_sidebar, body, li[data-contact-id="<%= @contact.uid %>"]').addClass('editing');
$('#form_container').html("<%= j render 'form' %>");

app/views/contacts/index.html.erb
<% title "Contacts" %>


<div class="bucket">
	<div class="bucket-body">
		<% if @contacts.present? %>
			<ul id="contacts">
			  <% @contacts.each do |contact| %>
			    <%= render contact %>
			  <% end %>
			</ul>
		<% else %>
			<% if params[:search].present? %>
				<% if params[:group].present? %>
					<p style="padding:15px 0 0;text-align:center;">There are no contacts matching your search in this group. <%= link_to "Search All Groups", contacts_path(group: nil, search: params[:search]) %></p>
				<% else %>
					<p style="padding:15px 0 0;text-align:center;">There are no contacts matching your search for "<%= params[:search] %>".</p>
				<% end %>
			<% else %>
				<p style="padding:15px 0 0;text-align:center;">There are no contacts in this group yet.</p>
			<% end %>
		<% end %>
	</div>
</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/new.js.erb
$('.contact').removeClass('editing')
$('#right_sidebar, body').addClass('editing');
$('#form_container').html("<%= j render 'form' %>")

app/views/contacts/show.html.erb
<% title @contact.name %>

<div class="bucket">
  <div class="bucket-header">
    <h3>Contact Info</h3>
  </div>
  <div class="bucket-body bucket-padding">
    <div class="row">
      <div class="col-md-6">
        <dl class="dl-horizontal">
          <dt>Email</dt><dd><%= @contact.email %></dd>
          <dt>Phone</dt><dd><%= @contact.phone %></dd>
          <dt>Transaction Type</dt><dd><span class="label label-info"> <%= @contact.pretty_transaction %></span> </dd>
          <% if @contact.company.present? %>
            <dt>Company</dt><dd> <%= @contact.company %></dd>
          <% end %>
          <% if @contact.service.present?  %>
            <dt>Service</dt><dd><%= @contact.service %> </dd>
          <% end %>
        </dl>
      </div>
      <div class="col-md-6">
        <dl class="dl-horizontal">
          <dt>Street</dt><dd><%= @contact.street %></dd>
          <dt>City</dt><dd><%= @contact.city %></dd>
          <dt>State</dt><dd><%= @contact.state %></dd>
          <dt>Zipcode</dt><dd><%= @contact.postal_code %></dd>
        </dl>
      </div>
    </div>
    <dl class="dl-horizontal">
      <dt>Notes</dt><dd><%= @contact.notes %></dd>
    </dl>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-6">
    <div class="bucket">
      <div class="bucket-header">
        <h3>Tasks</h3>
        <div class="bucket-actions">
          <%= link_to new_task_path(contact_id: @contact.uid), remote: true do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </div>
      </div>
      <% if @tasks.present? || params[:assigned_to] %>
        <div class="bucket-subheader">
          <div class="bucket-actions">
            <%= form_tag contact_path(@contact), method: :get do |f| %>
            <div class="field">
              <%= label_tag :assigned_to,  class: "select" do %>
                <%= select_tag :assigned_to, options_from_collection_for_select(User.all, :name, :name, selected: params[:assigned_to].present? ? params[:assigned_to] : nil), prompt: "Assigned To" %>
              <% end %>
            </div>
          <% end %>
          </div>
        </div>
      <% end %>
      <div class="bucket-body">
        <% if @tasks.present? %>
          <div id="tasks">
            <%= render "tasks/tasks", tasks: @tasks %>
          </div>
        <% else %>
          <% if params[:assigned_to].present? %>
            <p style="padding:15px 0 0;text-align:center;">There are currently no pending tasks for "<%= params[:assigned_to] %>".</p>
          <% else %>
            <p style="padding:15px 0 0;text-align:center;">There are currently no pending tasks.</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="bucket">
      <div class="bucket-header">
        <h3>Comments</h3>
        <div class="bucket-actions">
          <%= link_to new_contact_path(group: "client"), remote: true do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </div>
      </div>
      <div class="bucket-body">
        <div id="comments" class="comment-scroll">
          <%= render "comments/comments" %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/update.js.erb
$('#right_sidebar, body').removeClass('editing');
$('#form_container').html(" ");
$('#activities').html("<%= j render 'public_activity/activity_list' %>")
$('li[data-contact-id="<%= @contact.uid %>"] .name').text('<%= @contact.name %>')
$('li[data-contact-id="<%= @contact.uid %>"] .details').text('<%= @contact.transaction_type.gsub("_", " ").titleize %>')
$('li[data-contact-id="<%= @contact.uid %>"] .email').text('<%= @contact.email %>')
$('li[data-contact-id="<%= @contact.uid %>"] .phone').text('<%= @contact.phone %>')

app/views/contacts/view_comments.js.erb
$('#modals').html('<%= j render "comments/comments_modal", contact: @contact %>')
$('.modal').modal({
  keyboard: false,
  show: true,
  backdrop:true
})

	if ($("#comments ul").length > 0) {
		setTimeout(function(){
			$('#comments ul').scrollTop($('#comments ul').prop('scrollHeight'));
		},300)
	}